
server:
  port: ${PORT:8080}

spring:
  datasource:
    initialization-mode: always
    driver-class-name: org.postgresql.Driver
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5433/vv}
    username: postgres
    password: 0

  jpa:
    show-sql: true
    generate-ddl: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQL9Dialect

