version: '3.9'

services:
  postgres:
    build:
      context: services/postgres
      dockerfile: Dockerfile.development
    ports:
      - "5433:5432"
#    jdbc:postgresql://localhost:5433/db1
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_DB=db1
      - POSTGRES_PASSWORD=0
    volumes:
      - "db-data:/var/lib/postgresql/data"

  java1:
    build:
      context: services/java1
      dockerfile: Dockerfile.development

    environment:
      - PORT=8081
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres/db1
      - JS_URL=http://localhost
    image: 'java-one'
    ports:
      - 8081:8081
    depends_on:
      - postgres

  java2:
    build:
      context: services/java2
      dockerfile: Dockerfile.development

    environment:
      - PORT=8082
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres/db1
      - JS_URL=http://localhost
    image: 'java-two'
    ports:
      - 8080:8080
    depends_on:
      - postgres

  java3:
    build:
      context: services/java3
      dockerfile: Dockerfile.development
#      r2dbc:postgresql://localhost:5433/vv
    environment:
      - PORT=8083
      - SPRING_DATASOURCE_URL=r2dbc:postgresql://postgres/db1
      - JS_URL=http://localhost
    image: 'java-three'
    ports:
      - 8083:8083
    depends_on:
      - postgres


  js1:
    build:
      context: services/js1
      dockerfile: Dockerfile.development
    image: 'js-one'
    ports:
        - 80:80

  js2:
    build:
      context: services/js2
      dockerfile: Dockerfile.development
    image: 'js-two'
    ports:
      - 81:80

volumes:
   db-data: